{
 "title": "Custos",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_name",
    "label": "Account Name",
    "query": "{\"find\": \"terms\", \"field\": \"line_item_usage_account_name.keyword\"}"
   },
   {
    "name": "account_id",
    "label": "Account Id",
    "query": "{\"find\": \"terms\", \"field\": \"line_item_usage_account_id.keyword\", \"query\": \"line_item_usage_account_name.keyword:$account_name\"}"
   },
   { "name": "interval", "label": "interval", "query": "1d,1w,1M" },
   {
    "name": "aws_used_services",
    "label": "AWS Services",
    "query": "{\"find\": \"terms\", \"field\": \"line_item_product_code.keyword\", \"query\": \"line_item_usage_account_id.keyword:$account_id\", \"orderBy\": \"doc_count\", \"order\": \"desc\"}"
   },
   {
    "name": "data_transfer_type",
    "label": "data_transfer_type",
    "query": "{\"find\": \"terms\", \"field\": \"line_item_usage_type.keyword\", \"query\": \"line_item_usage_account_id.keyword:$account_id AND  (   line_item_product_code:*aws* OR    line_item_product_code: *amazon* ) AND line_item_usage_type:datatransfer\"}"
   }
  ]
 },
 "panels": [
  { "title": "Current Month Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Monthly Cost (time window)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Top Services",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_product_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND (line_item_product_code:*aws* OR line_item_product_code: *amazon*)",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Pricing Term",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pricing_term.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND \n(line_item_product_code.keyword:AmazonEC2 OR\nline_item_product_code.keyword:AmazonRDS OR line_item_product_code.keyword:ComputeSavingsPlans)",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Top EC2 Instance Types",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_instance_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND (line_item_product_code.keyword:AmazonEC2 OR line_item_product_code.keyword:ComputeSavingsPlans)",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Top RDS Instance Types",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_instance_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword:AmazonRDS",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Tax",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tax",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_net_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND line_item_line_item_type.keyword: Tax",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Premium Support",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Premium Support",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_net_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": " line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword: AWSSupportEnterprise AND NOT line_item_line_item_type.keyword: Tax",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Discount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Discount",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND line_item_line_item_type.keyword: EdpDiscount OR\nline_item_line_item_type.keyword: PrivateRateDiscount",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Top Data Transfer Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_usage_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Top Data Transfer Product",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_product_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "product_region_code.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND line_item_unblended_cost: >0",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "S3 Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_resource_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": " line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword:AmazonS3",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "RDS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_resource_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword:AmazonRDS",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  { "title": "Overview History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Cost by Charge Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_line_item_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND NOT \nline_item_product_code.keyword:AWSSupportEnterprise AND NOT\nbill_billing_entity.keyword:\"AWS Marketplace\" AND NOT\n(\nline_item_line_item_type.keyword:DiscountedUsage OR \nline_item_line_item_type.keyword:SavingsPlanNegation OR\nline_item_line_item_type.keyword:SavingsPlanCoveredUsage OR\nline_item_line_item_type.keyword:Tax\n)",
     "timeField": "line_item_usage_start_date"
    },
    {
     "alias": "Enterprise Support",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "$interval", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_net_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND\nline_item_product_code.keyword:AWSSupportEnterprise AND NOT line_item_line_item_type.keyword: Tax",
     "timeField": "line_item_usage_start_date"
    },
    {
     "alias": "Tax",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_net_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND\nline_item_line_item_type.keyword: Tax",
     "timeField": "line_item_usage_start_date"
    },
    {
     "alias": "Marketplace",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_net_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "bill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Marketplace Cost by Entity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_legal_entity.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND\nbill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Total Costs by Account",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_usage_account_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND NOT bill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND NOT bill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    },
    {
     "alias": "MoM Change",
     "bucketAggs": [
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      {
       "field": "line_item_unblended_cost",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND NOT bill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Pricing Term - EC2",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pricing_term.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND \n(line_item_product_code.keyword:AmazonEC2 OR\n line_item_product_code.keyword:ComputeSavingsPlans)",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Total Costs by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "line_item_product_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND NOT bill_billing_entity.keyword:\"AWS Marketplace\"",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Pricing Term - RDS",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "pricing_term.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "1M", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
     ],
     "query": "line_item_usage_account_id.keyword:$account_id AND \nline_item_product_code.keyword:AmazonRDS",
     "timeField": "line_item_usage_start_date"
    }
   ]
  },
  {
   "title": "Services Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$aws_used_services",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 36 },
     "repeat": "aws_used_services",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "line_item_usage_type.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "$interval", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
       ],
       "query": " line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources by Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$aws_used_services",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
     "repeat": "aws_used_services",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "line_item_resource_id.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "line_item_usage_start_date", "id": "2", "settings": { "interval": "$interval", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "field": "line_item_unblended_cost", "id": "1", "type": "sum" }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND line_item_product_code.keyword:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Transfer by Service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "line_item_product_code.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "line_item_usage_start_date",
         "id": "6",
         "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "line_item_unblended_cost",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer AND \nline_item_product_code:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "field": "line_item_usage_start_date",
         "id": "6",
         "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "line_item_unblended_cost",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer AND \nline_item_product_code:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      }
     ]
    },
    {
     "title": "Data Transfer by Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "line_item_usage_type.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "line_item_usage_start_date",
         "id": "6",
         "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "line_item_unblended_cost",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer AND \nline_item_product_code:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      },
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "field": "line_item_usage_start_date",
         "id": "6",
         "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "line_item_unblended_cost",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer AND \nline_item_product_code:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      }
     ]
    },
    {
     "title": "Data Transfer by Resource - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "line_item_resource_id.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "field": "line_item_usage_start_date",
         "id": "6",
         "settings": { "interval": "$interval", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        {
         "field": "line_item_unblended_cost",
         "id": "1",
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "line_item_usage_account_id.keyword:$account_id AND \n(\n  line_item_product_code:*aws* OR \n  line_item_product_code: *amazon*\n) AND\nline_item_usage_type:datatransfer AND \nline_item_product_code:$aws_used_services",
       "timeField": "line_item_usage_start_date"
      }
     ]
    }
   ]
  }
 ]
}