networks:
  backend:
    driver: bridge

services:

  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    platform: linux/x86_64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - search.max_buckets=900000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PWD}/volumes/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 30

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    platform: linux/x86_64
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      elasticsearch:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss:11.1.5
    container_name: grafana
    hostname: grafana
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ${PWD}/docker/infra/grafana/fs/volumes/grafana/etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${PWD}/docker/infra/grafana/fs/volumes/grafana/etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ${PWD}/docker/infra/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "0.0.0.0:3000:3000"

  cur:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    container_name: cur
    hostname: cur
    env_file:
      - ${PWD}/docker/env
    volumes:
      - ${PWD}/src:/app/
      - ${PWD}/parquet_files:/tmp/parquet_files
