apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: aws-cur-v2*
    isDefault: true
    url: "http://elasticsearch:9200"
    readonly: false
    jsonData:
      esVersion: 7.10.0
      maxConcurrentShardRequests: 5
      timeField: "line_item_usage_start_date"